// Generated by Wrangler by running `wrangler types`

interface Env {
	NUSACLOUD_ENV: "production";
	ROOM: DurableObjectNamespace<import("./src/index").RoomDO>;
	BUCKET_BACKUPS: R2Bucket;
	BUCKET_IMAGES: R2Bucket;
	BUCKET_THUMBS: R2Bucket;
	DB: D1Database;
}
